import { CodeEditor } from "@/components/codeEditor/CodeEditor";
import styles from "./page.module.css";
import { Table_text } from "@/components/table_text/Table_text";
import { QuestionOneTest } from "@/components/questions/QuestionOneTest";



export default function Home() {
  return (
    <main className={styles.main}>
     <Table_text
      question="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 
       sssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssss
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s/n
       ssss
       aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 
       sssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssss
       
       aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 
       sssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssss
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s/n
       ssss
       aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 
       sssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssss
       aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 
       sssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssss
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s/n
       ssss
       aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 
       sssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssss
       aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 
       sssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssss
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s/n
       ssss
       aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 
       sssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssss
       aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 
       sssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssss
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s/n
       ssss
       aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 
       sssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssss
       aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 
       sssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssss
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s
       s/n
       ssss
       aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 
       sssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssssssssssss
       ssssssssssssssssssssssssssssssssssssssssssssssss
       "
       methods="" responseJS="" responseTS=""/>
    </main>
  );
}
